<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm2.aspx.cs" Inherits="WebApplication3.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
            <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Button" />
            <asp:GridView ID="GridView1" DataKeyNames="eid" runat="server"  AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="edit" OnRowCancelingEdit="cancel" OnRowDeleting="del" OnRowUpdating="updating" AutoGenerateColumns="False" OnRowUpdated="updated" >
        
                <Columns>
         
        <asp:TemplateField HeaderText="ID">
            <ItemTemplate>
                <asp:Label ID="ID" runat="server" Text='<%#Bind("eid")%>'></asp:Label>                                         
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Name">
            <ItemTemplate>
                <asp:Label ID="NAME" runat="server" Text='<%#Bind("firstname")%>'></asp:Label>
            </ItemTemplate>
             <EditItemTemplate>
                 <asp:Textbox ID= "Name" runat="server" AutoPostBack="true"  Text='<%#Bind("firstname")%>'></asp:Textbox>
            </EditItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Salary">
            <ItemTemplate>
                <asp:Label ID="Salary" runat="server" Text='<%#Bind("salary")%>'></asp:Label>
            </ItemTemplate>
             <EditItemTemplate>
                 <asp:Textbox ID= "salary" runat="server" AutoPostBack="true"  Text='<%#Bind("salary")%>'></asp:Textbox>
            </EditItemTemplate>
            <FooterTemplate>
                <asp:Label ID="lblTotal1" runat="server"></asp:Label>
            </FooterTemplate>
        </asp:TemplateField>
        <asp:TemplateField>
            <ItemTemplate>
            </ItemTemplate>
            <EditItemTemplate>
            </EditItemTemplate>
        </asp:TemplateField>
       
    </Columns>
                
            </asp:GridView>
        </div>
    </form>
</body>
</html>
